---
title: "Exercício 11 - Visualização de Dados"
author: "Saulo Ferreira"
date: "12/07/2020"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Questões {.tabset}

## Questão 1

```{r echo=F, fig.width=7, fig.height=10}
MRT_1F <-c(517.1468515630205, 85.13094142168089, 30.333207896694553, 12.694776264558937, 3.3041601673945418, 1.1823111717498882, 1.1892293502386786)
MRT_3F <-c(156.68929936163462, 11.540837783562276, 0.4512835621696538, 0.4509797929766453, 0.4502068233039181, 0.4496185276300172, 0.4543157082191288)
MRT_5F <-c(83.90319666471157, 0.3068151086494968, 0.30522314133037304, 0.3072588968084928, 0.30655265997285697, 0.3055812715727718, 0.3053297166713006)
MRT_10F <-c(29.55430642951759, 0.19832832665772515, 0.1971923924717474, 0.19796648905716516, 0.19615594370806338, 0.2034569237883263, 0.19617420889447737)
MRT_15F <-c(11.317736530583566, 0.167364215666193, 0.16172168266811013, 0.16701085329580515, 0.1598052657153692, 0.1645934043532696, 0.16216563797118075)
MRT_sem_F <-c(11.93430909937736, 0.6095414637034009, 0.6060645101029295, 0.612167181646899, 0.6146761002685637, 0.6096747087200697, 0.6125810476877268)

clock <- c(0.1, 0.5, 1, 1.5, 2, 2.5, 3)

layout(matrix(c(1,1,1,1,2,3,4,5,6,0), 5, 2, byrow = T))

plot(clock, MRT_1F,
     type="o",
     pch=4,
     xlim=c(0,3),
     ylim=c(0,500),
     xlab="Time between Things requests (seconds)",
     ylab="Response Time (sec.)",
     cex=1) 
lines(MRT_3F, type="o", col="yellow", pch=11)
lines(MRT_5F, type="o", col="red", pch=1)
lines(MRT_10F, type="o", col="purple", pch=2)
lines(MRT_15F, type="o", col="pink", pch=5)
lines(MRT_sem_F, type="o", col="green", pch=4)

legend("topright",
       pch=c(4,11,1,2,5,4),
       col=c("black", "yellow", "red", "purple", "pink", "green"),
       legend=c("1 Fog", "3 Fog", "5 Fog", "10 Fog", "15 Fog", "w/o Fog"))

values <- matrix(c(MRT_sem_F, MRT_1F), nrow=2, ncol=7, byrow=T)
barplot(values,
        log="y",
        xlab="Time between Things requests",
        ylab="Response time (s)",
        names.arg = clock,
        col=c("#E6E6E6", "#666666"),
        beside=T)

legend("topright",
       pch=c(15,15),
       col=c("#E6E6E6", "#666666"),
       legend=c("w/o Fog","1 Fog"))

values <- matrix(c(MRT_sem_F, MRT_3F), nrow=2, ncol=7, byrow=T)
barplot(values,
        log="y",
        xlab="Time between Things requests",
        ylab="Response time (s)",
        names.arg = clock,
        col=c("#E6E6E6", "#666666"),
        beside=T)

legend("topright",
       pch=c(15,15),
       col=c("#E6E6E6", "#666666"),
       legend=c("w/o Fog","3 Fog"))

values <- matrix(c(MRT_sem_F, MRT_5F), nrow=2, ncol=7, byrow=T)
barplot(values,
        log="y",
        xlab="Time between Things requests",
        ylab="Response time (s)",
        names.arg = clock,
        col=c("#E6E6E6", "#666666"),
        beside=T)

legend("topright",
       pch=c(15,15),
       col=c("#E6E6E6", "#666666"),
       legend=c("w/o Fog","5 Fog"))

values <- matrix(c(MRT_sem_F, MRT_10F), nrow=2, ncol=7, byrow=T)
barplot(values,
        log="y",
        xlab="Time between Things requests",
        ylab="Response time (s)",
        names.arg = clock,
        col=c("#E6E6E6", "#666666"),
        beside=T)

legend("topright",
       pch=c(15,15),
       col=c("#E6E6E6", "#666666"),
       legend=c("w/o Fog","10 Fog"))

values <- matrix(c(MRT_sem_F, MRT_15F), nrow=2, ncol=7, byrow=T)
barplot(values,
        log="y",
        xlab="Time between Things requests",
        ylab="Response time (s)",
        names.arg = clock,
        col=c("#E6E6E6", "#666666"),
        beside=T)

legend("topright",
       pch=c(15,15),
       col=c("#E6E6E6", "#666666"),
       legend=c("w/o Fog","15 Fog"))

```

## Questão 2
```{r echo=F}
price10 = c(53.8, 43.6, 2.6)
price20 = c(33.9, 54.2, 11.9)
price30 = c(2.6, 60.5, 36.8)
price40 = c(0, 21.4, 78.6)

categories = c("Good", "Very Good", "Excellent")
colors <- c("yellow", "green", "blue")

values = matrix(c(price10,price20,price30,price40), nrow = 3, ncol = 4)
barplot(values,
        main="Feedback da carne pelo preço",
        names.arg=c("$10-19", "$20-29", "$30-39", "$40-49"),
        xlab="Preços",ylab="Percentual",
        col=colors,
        beside = F)
legend("right", pch=c(15,15,15), col=colors, legend=categories)
```

## Questão 3
```{r echo=F, error=F, message=F, warning=F}
library(dplyr)

data = airquality %>% filter(Month==5) %>% select(Temp, Day)
data$Temp = (data$Temp-32)/1.8
dens = density(data$Temp)

hist(data$Temp,
     col="grey",
     main = "Histogramas das Temperaturas do Mês de Maio",
     xlab="Temperatura",
     ylab="Frequência",
     breaks=5,
     probability = T)
lines(dens)
```

## Questão 4
```{r echo=F}
sales <- read.table("https://training-course-material.com/images/8/8f/Sales.txt",header=TRUE)
pct <- round(sales$SALES/sum(sales$SALES)*100)
lbls <- paste(pct, "%", sep="")

pie(sales$SALES,
    lbls,
    main="Porcentagem de Vendas por País",
    col = c("yellow","purple","grey","orange","blue","red"))

legend("topleft",
       legend=sales$COUNTRY,
       pch=15,
       col=c("yellow","purple","grey","orange","blue","red"))
```

## Questão 5
```{r echo=F}
boxplot(InsectSprays$count ~ InsectSprays$spray,
        outline=F,
        xlab="Sprays",
        ylab="Contagem",
        main="Distribuição da Contagem de Insetos por Inseticida",
        col="yellow")
```

## Questão 6
```{r echo=F}
plot(mtcars$wt,
     mtcars$mpg,
     xlab="Peso",
     ylab="Milhas Percorridas",
     main="Peso/Milhas Percorridas",
     pch=16)
lines(lowess(mtcars$wt,mtcars$mpg), col = "blue")
```
